apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  selector:
    app: activemq
    leader: "yes"
  ports:
    - name: dashboard
      port: 8161
      targetPort: dashboard
      protocol: TCP
    - name: openwire
      port: 61616
      targetPort: openwire
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: stomp
      port: 61613
      targetPort: stomp
      protocol: TCP
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.1
